# @package _global_
defaults:
  - /sweep/tune_base
  - override /model: efficientkan
  - override /training: adam

hydra:
  sweeper:
    params:
      optimizer: choice(adam, adamw, sgd)
      model.grid_size: range(3, 51)
      optimizer.lr: tag(log, interval(0.001, 1.0))
      ++optimizer.weight_decay: tag(log, interval(1e-6, 1e-2))
      ++optimizer.momentum: interval(0.0, 0.99)
