_target_: src.models.faster_kan_model.FasterKANModel
n_hidden_layers: 1
hidden_width: 5
layers_hidden: ${make_width:${dataset.input_dim},${dataset.output_dim},${model.n_hidden_layers},${model.hidden_width}}
grid_min: -1.2
grid_max: 1.2
num_grids: 8
