_target_: src.models.kagnconv_model.KAGNConv4Model

num_classes: ${dataset.output_dim}
input_channels: ${dataset.in_chans}
img_size: ${dataset.img_size}

# 4-layer baseline channels from Drokin (2024), Sec. 4.1
layer_sizes: [32, 64, 128, 512]

degree: 3
degree_out: 3
groups: 1
dropout: 0.0
dropout_linear: 0.0
l1_penalty: 0.0
affine: true
