_target_: src.models.wavkan_model.WavKANModel
n_hidden_layers: 1
hidden_width: 5
layers_hidden: ${make_width:${dataset.input_dim},${dataset.output_dim},${model.n_hidden_layers},${model.hidden_width}}
wavelet_type: mexican_hat
