hydra:
  run:
    dir: .

experiment_name: experiment
mlflow_tracking_uri: sqlite:///mlflow.db

trainer:
  _target_: src.training.trainer.Trainer

defaults:
  - model: pykan
  - dataset: bessel
  - training: default
  - _self_
