# @package _global_
defaults:
  - tune_base
  - override /model: fastkan
  - override /training: adam

hydra:
  sweeper:
    params:
      model.num_grids: range(4, 33)
      training.optimizer: choice(Adam)
      training.lr: tag(log, interval(0.001, 1.0))
