# @package _global_
defaults:
  - tune_base
  - override /model: efficient_kan
  - override /training: adam

training.optimizer: Adam
model.grid: 20

hydra:
  sweeper:
    params:
      # same spline order range as pykan (equivalent parameter)
      model.k: range(2, 6)
