# @package _global_
defaults:
  - tune_base
  - override /model: efficient_kan
  - override /training: adam

hydra:
  sweeper:
    params:
      model.grid_size: range(3, 51)
      model.grid_update_freq: range(5, 30)
      training.optimizer: choice(Adam)
      training.lr: tag(log, interval(0.001, 1.0))
